### ISSUE TITLE
Merging of corpora

### ISSUE THREAD

**Issue by Ninoninoninonino** [ropensci/textreuse#74]
I'm downloading several years of website content from the Internet Archive and I would like to assign metadata based on years to them. How can I use TextReuse in order to remove duplicates from merged corpora, in a way that leaves the first duplicate instance and removes the subsequent ones? 

I just confirmed that TextReuse corpora have inherited the meta data assignment capability from TM corpora. However, the merging of corpora doesn't work the TM way.

**Comment by lmullen** [comment]
It is not possible for me to provide guidance on how to use the package for specific applications, so I am closing this issue. If you can report a specific bug supported by code to reproduce the bug, I will reopen it.

**Comment by Ninoninoninonino** [comment]
Thanks, I used _digest_ in order to assign MD5 hashes and then get rid of 100% duplicates. I see now that Minhashes are only necessary for more fuzzy similiarity measures.
