### ISSUE TITLE
Apparently `min(bitwXor(h, i)` is fed a double at times when it wants integers

### ISSUE THREAD

**Issue by ecoquant** [ropensci/textreuse#84]
`R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
`

Windows 7 HE, latest updates.

`mhg<- minhash_generator(n=128)`

```
> w.trc<- TextReuseCorpus(text=w.all, tokenizer=function(w) tokenize_words(w,lowercase=FALSE), keep_text=TRUE, keep_tokens=FALSE, skip_short=FALSE, hash_func=hash_string, minhash_func=mhg)
```
Loading, tokenizing, and hashing **19,122,982** documents.

  |                                                                                                                                                                                               
  |                                                                                                                                                                                         |   0%
  |                                                                                                                                                                                               
  |=                                                                                                                                                                                        |   0%
  |                                                                                                                                                                                               
  |=                                                                                                                                                                                        |   1%
  |                                                                                                                                                                                               
  |==                                                                                                                                                                                       |   1%
  |                                                                                                                                                                                               
  |===                                                                                                                                                                                      |   1%
  |                                                                                                                                                                                               
  |===                                                                                                                                                                                      |   2%Warning in min(bitwXor(h, i)) :
  no non-missing arguments to min; returning Inf
Error in vapply(r, function(i) { : values must be type 'integer',
 but FUN(X[[1]]) result is type 'double'
> traceback()
6: vapply(r, function(i) {
       min(bitwXor(h, i))
   }, integer(1), USE.NAMES = FALSE)
5: minhash_func(tokens)
4: TextReuseTextDocument(text = text[i], tokenizer = tokenizer, 
       ..., hash_func = hash_func, minhash_func = minhash_func, 
       keep_tokens = keep_tokens, keep_text = keep_text, skip_short = skip_short, 
       meta = list(id = names(text)[i], tokenizer = tokenizer_name, 
           hash_func = hash_func_name, minhash_func = minhash_func_name))
3: FUN(X[[i]], ...)
2: apply_func(seq_along(text), function(i) {
       d <- TextReuseTextDocument(text = text[i], tokenizer = tokenizer, 
           ..., hash_func = hash_func, minhash_func = minhash_func, 
           keep_tokens = keep_tokens, keep_text = keep_text, skip_short = skip_short, 
           meta = list(id = names(text)[i], tokenizer = tokenizer_name, 
               hash_func = hash_func_name, minhash_func = minhash_func_name))
       if (progress) 
           setTxtProgressBar(pb, i)
       d
   })
1: TextReuseCorpus(text = w.all, tokenizer = function(w) tokenize_words(w, 
       lowercase = FALSE), keep_text = TRUE, keep_tokens = FALSE, 
       skip_short = FALSE, hash_func = hash_string, minhash_func = mhg)
>
```


First few lines of `w.all` are:

`> head(w.all)
                                                                                                                                                                   > 
[1] "15E302"                                                                                                                                                                 
[2] "Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/66.0.3359.181%20Safari/537.36"                              
[3] "OfficeClickToRun"                                                                                                                                                       
[4] "Mozilla/5.0%20(iPhone;%20CPU%20iPhone%20OS%2011_3%20like%20Mac%20OS%20X)%20AppleWebKit/605.1.15%20(KHTML,%20like%20Gecko)%20Version/11.0%20Mobile/15E148%20Safari/604.1"
[5] "pipelined/380.0.4%20CFNetwork/897.15%20Darwin/17.5.0"                                                                                                                   
[6] "Mozilla/5.0%20(Windows%20NT%206.1;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/66.0.3359.181%20Safari/537.36"                               
>`

I am grabbing a source copy of `TextReuseCorpus` and attempting to isolate.

**Comment by lmullen** [comment]
A reproducible example would help a great deal in debugging.

Are you able to successfully run the code on a small subset of the corpus?

What arguments are you using to create your minhash function `mhg`?

Are any of the documents in the corpus extremely large? What value do you get for `.Machine$integer.max`?

**Comment by ecoquant** [comment]
I have isolated this.  TextreuseCorpus fails when fed a string solely consisting of an open and close brace, as ``{}''.

```
> w.trc<- TextReuseCorpus(text=w.part.stripped[c(51555,51555)], tokenizer=function(w) tokenize_words(w,lowercase=FALSE), keep_text=TRUE, keep_tokens=FALSE, skip_short=FALSE, hash_func=hash_string, minhash_func=mhg, progress=FALSE)
> w.trc<- TextReuseCorpus(text=w.part.stripped[c(51555,51557)], tokenizer=function(w) tokenize_words(w,lowercase=FALSE), keep_text=TRUE, keep_tokens=FALSE, skip_short=FALSE, hash_func=hash_string, minhash_func=mhg, progress=FALSE)
Warning in min(bitwXor(h, i)) :
  no non-missing arguments to min; returning Inf
Error in vapply(r, function(i) { : values must be type 'integer',
 but FUN(X[[1]]) result is type 'double'
> w.part.stripped[51555]
[1] "Mozilla/5.0 (1905MB; 1024x552; 160x160; 1024x552; LENOVO Lenovo TB-7304I; 7.0) AppleWebKit/537.36 (KHTML, like Gecko)  ROBLOX Android App 2.339.208477 Tablet Hybrid()  GooglePlayStore"
> w.part.stripped[51557]
[1] "{}"
> 

```

**Comment by ecoquant** [comment]
```
> .Machine$integer.max
[1] 2147483647
```

**Comment by lmullen** [comment]
I'm not sure what I will do with this if anything, if that is the case. The problem is essentially that you are passing in a document with no text. The argument `skip_short`, which you've disabled, is intended to remove documents which are too short to be compared with one another. If you don't want `TextReuseCorpus()` to do that kind of checking for you, then it is the user's responsibility to filter out documents which cannot be compared. The most likely change that I would make is to produce a better error message for very short documents, though there is already an informative error message when `skip_short = TRUE` (as by default).

```
> TextReuseCorpus(text = c(a = "{}", b = "This document is long enough for our purposes."))
Loading, tokenizing, and hashing 2 documents.
  |======================================================================| 100%
TextReuseCorpus
Number of documents: 1
hash_func : hash_string
tokenizer : tokenize_ngrams
Warning messages:
1: Skipping document with ID 'a' because it has too few words to create at least two n-grams with n = 3.
2: In TextReuseCorpus(text = c(a = "{}", b = "This document is long enough for our purposes.")) :
  Skipped 1 documents that were too short. Use `skipped()` to get their IDs.
```

**Comment by ecoquant** [comment]
Okay. Thanks. 

Is there some way of suppressing that warning?  If I skip too short documents it won't have any effect upon the result I want, since they are not meaningful.

**Comment by lmullen** [comment]
You can always suppress warnings with the `suppressWarnings()` function.
