### ISSUE TITLE
jaccard_similarity result?

### ISSUE THREAD

**Issue by bihappywater** [ropensci/textreuse#86]
Hi, 
Is that strange to see  jaccard_similarity ("abcdef","abc")  = 0 ?  I would expect to get 0.5. 
I have textreuse version at 0.1.4

Thank you in advance for your kind help!

**Comment by lmullen** [comment]
@bihappywater The `jacquard_similarity()` function expects a character vector, and each element is compared. You need to decide how to tokenize the strings you pass in. For instance, you want those "documents" split into characters. This gives the answer you are expecting:

```
jaccard_similarity(c("a", "b", "c", "d", "e", "f"), c("a", "b", "c"))
```

See the functions that begin with `tokenize_*` in this package or the [tokenizers](https://lincolnmullen.com/software/tokenizers/) package.
