### ISSUE TITLE
align_local documentation

### ISSUE THREAD

**Issue by under-score** [ropensci/textreuse#94]
How do the scores in the align_local output relate to the #### marks in the a_edits list text?

**Comment by lmullen** [comment]
They are directly related, but they are not related in a way that you would use. The `###` marks show the position of edits in the two longest matching substrings. There are, however, many different potential matching substrings. The Smith-Waterman algorithm computes which substring is the best by using scores for matching characters, penalties for gaps, etc. The score reported is the score for the longest substring, which by definition is higher than all the other potential matching substrings. To see how that score is computed, you can [read about the algorithm](https://en.wikipedia.org/wiki/Smith–Waterman_algorithm).

**Comment by under-score** [comment]
thank you
